CREATE TABLE IF NOT EXISTS sets (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year      SMALLINT,
    publisher VARCHAR(255),
    name      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bowman_checklists (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no     VARCHAR(255),
    player VARCHAR(255),
    auto   BOOLEAN,
    set_id INTEGER,
    CONSTRAINT fk_bowman_checklists_set FOREIGN KEY (set_id) REFERENCES sets(id)
);
