-- Baseline schema: documents tables created before Flyway was introduced.
-- This script is NOT executed against an existing database (baseline-on-migrate=true marks it as already applied).
-- It WILL run when setting up a fresh database from scratch.

CREATE TABLE cards (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year    VARCHAR(255),
    publisher VARCHAR(255),
    "set"   VARCHAR(255),
    player  VARCHAR(255),
    auto    BOOLEAN,
    "insert" VARCHAR(255),
    parallel VARCHAR(255),
    numbered VARCHAR(255),
    sports  VARCHAR(255),
    grade   VARCHAR(255),
    value   NUMERIC,
    note    VARCHAR(255),
    type    VARCHAR(255)
);

CREATE TABLE transactions (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date   DATE,
    type   VARCHAR(255),
    amount NUMERIC,
    note   VARCHAR(255)
);

CREATE TABLE transaction_infos (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INTEGER,
    card_id        INTEGER,
    move           VARCHAR(255)
);

CREATE TABLE search_keywords (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword          VARCHAR(255),
    last_id          VARCHAR(255),
    last_search_time TIMESTAMP
);
