CREATE TABLE recommendations (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player     VARCHAR(255) NOT NULL,
    sport      VARCHAR(20)  NOT NULL,
    reason     VARCHAR(120),
    author     VARCHAR(10)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);
