CREATE TABLE storages (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT       NOT NULL,
    CONSTRAINT fk_storages_user FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE cards ADD COLUMN storage_id BIGINT;
ALTER TABLE cards ADD CONSTRAINT fk_cards_storage
    FOREIGN KEY (storage_id) REFERENCES storages(id) ON DELETE SET NULL;
